### ISSUE TITLE
List Issue

### ISSUE THREAD

**Issue by wolflord212312** [JustRed23/ABCM#5]
**Description of issue**
Was implementing a list but found when i edit away from the default value for the list it causes issues/not loading config files, i did DM you on Discord About it this is just a reminder I am to lazy to dig up all the info again As i have not slept 

ERROR:
```
Caused by: dev.JustRed23.abcm.exception.ConfigInitException: Could not initialize configurables, check your terminal for more information
        at dev.JustRed23.abcm.Config.apply(Config.java:528)
        at dev.JustRed23.abcm.Config.init(Config.java:179)
        at me.djjewl.Main.main(Main.java:34)
        Suppressed: dev.JustRed23.abcm.exception.ConfigInitException: Could not parse value of field ips
                at dev.JustRed23.abcm.Config.lambda$null$8(Config.java:518)
                at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
                at dev.JustRed23.abcm.Config.lambda$apply$9(Config.java:486)
                at java.base/java.util.HashMap$KeySet.forEach(HashMap.java:1008)
                at dev.JustRed23.abcm.Config.apply(Config.java:474)
                ... 2 more
```

**Comment by wolflord212312** [comment]
@JustRed23 Dont forgor lol Jk forgor if you want just get it fixed by the end of the year thx!
Also Have a good day at work!

**Comment by JustRed23** [comment]
I cannot seem to reproduce your issue. Do know that list values get stored in a json format when saved to the config, you can only add values separated by commas in the ConfigField defaultValue field
